### ISSUE TITLE
Question: Using mkdocs in flask

### ISSUE THREAD

**Issue by jdhaines** [ctsit/barebones-flask-app#7]
Hi,

I was wondering if you have had any success serving mkdocs html files from within flask.  I've been trying to get it to work and can't seem to find a decent way.  I can show a single page, or the pages once they've been converted to static html pages as long as I put in routes for each.  What I'd like to do is have the links generated within mkdocs serve the applicable page.  Flask-FlatPages has the correct functionality, but then you lose all the benefits of mkdocs styling, table of contents, etc.  

This is only partially directed at your project, but I saw you had mkdocs installed and didn't know if it was part of the app itself, or simply a way to host documentation for this app project.  Thanks.

**Comment by indera** [comment]
Josh, this repository is not intended to serve mkdocs html files from within flask. The only reason I have the mkdocs.yml file is to be able to have the documentation hosted on http://barebones-flask-app.readthedocs.org/en/latest/. I recommend you to try the same approach. You will have to create an account on the readthedocs.org website and point it to build the html files from the github repo.
